### ISSUE TITLE
调用clb的ModifyTargetWeight会返回错误

### ISSUE THREAD

**Issue by damienlsq** [TencentCloud/tencentcloud-sdk-nodejs#11]
调用参数都看过是正确的，
    `const filters = {
      LoadBalancerId: 'xxx',
      ListenerId: 'xxx',
      LocationId: 'xxx',

      Weight,
      Targets: [
        {
          InstanceId: 'xxx',
        },
      ],
    };
`
但返回下面内容：
{ Error: An internal error has occurred. Retry your request, but if the problem persists, contact us with details by posting a message on the Tencent cloud forums.
    at HttpConnection.doRequest (/data/polaris/node_modules/tencentcloud-sdk-nodejs/tencentcloud/common/abstract_client.js:98:45)
    at Request._callback (/data/polaris/node_modules/tencentcloud-sdk-nodejs/tencentcloud/common/http/http_connection.js:28:13)
    at Request.self.callback (/data/polaris/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/data/polaris/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/data/polaris/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
  requestId: 'b3bac0b7-ab7d-4a60-a1d7-273de44abd27',
  code: 'InternalError' }

**Comment by zqfan** [comment]
Target里的port也是个必填的参数，不过这个报错信息也不友好，后续API会完善下
