### ISSUE TITLE
DescribeCaptchaResult 报错没传SecretId

### ISSUE THREAD

**Issue by toknT** [TencentCloud/tencentcloud-sdk-nodejs#138]
```ts
        const CaptchaClient = tencentcloud.captcha.v20190722.Client;
        const captchaAppId = process.env.TENCENT_CAPTCHA_APPID;
        const captchaSecret = process.env.TENCENT_CAPTCHA_SECRET_KEY;
        const clientConfig = {
            credential: {
                secretId: captchaAppId,
                secretKey: captchaSecret,
            },
            region: 'ap-guangzhou',
        }
        console.warn('clientConfig', clientConfig);
        const client = new CaptchaClient(clientConfig);
        const request: DescribeCaptchaResultRequest = { CaptchaType: 9, Ticket: ticket, CaptchaAppId: parseInt(captchaAppId), AppSecretKey: captchaSecret, Randstr: randStr, UserIp: userIp };
        client.DescribeCaptchaResult(request).then(
            (data) => {
                console.log(data)
            },
            (err) => {
                console.error("error", err)
            }
        )
```

报错
```sh
clientConfig {
  credential: { secretId: '************', secretKey: '***********************************' },
  region: 'ap-guangzhou'
}
[Nest] 24732  - 2023/05/17 10:26:46    WARN !log it when env is local! 
error TencentCloudSDKHttpException [Error]: The SecretId is not found, please ensure that your SecretId is correct.
    at Client.parseResponse (C:\Users\toknsit\workspace\test_center\node_modules\tencentcloud-sdk-nodejs\tencentcloud\common\abstract_client.js:154:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Client.request (C:\Users\toknsit\workspace\test_center\node_modules\tencentcloud-sdk-nodejs\tencentcloud\common\abstract_client.js:76:28) {
  requestId: 'bfb18988-9cd4-4c3e-beef-83dd2e9574cc',
  code: 'AuthFailure.SecretIdNotFound'
}
```

目前公司申请的体验app😊
![cap](https://github.com/TencentCloud/tencentcloud-sdk-nodejs/assets/15935037/e612f485-ed42-4633-a9e9-0b43d483d0dd)

**Comment by zqfan** [comment]
这个报错是你secretid传错了，不是没传，可能是多复制了空格或者少复制了，你可以本地log一下看看到底是个什么值

**Comment by zqfan** [comment]
另外尽量不要真实控制台的截图，github是公开场合，如果有需要，可以到控制台工单系统了提单找内部人员看
