### ISSUE TITLE
在electron-vue项目中的使用？

### ISSUE THREAD

**Issue by caoxingshu** [TencentCloud/tencentcloud-sdk-nodejs#64]
把SKD作为模块导出到vue组件里会出现promisfy错误，请问是怎么回事

**Comment by caoxingshu** [comment]
错误信息：
internal/util.js:206 Uncaught NodeError: The "original" argument must be of type function
    at promisify (internal/util.js:206:11)
    at Object.<anonymous> (H:\paperIndentify\paper-indentify\node_modules\_get-stream@6.0.0@get-stream\index.js:7:35)
    at Object.<anonymous> (H:\paperIndentify\paper-indentify\node_modules\_get-stream@6.0.0@get-stream\index.js:63:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18

**Comment by PeiqiaiShanzhu** [comment]
请问你解决这个问题了么

**Comment by cyrilluce** [comment]
此sdk仅能用于nodejs环境，不能用于浏览器
