### ISSUE TITLE
和问题69 一样 在腾讯云serverless上，发送短信，报错没传SecretId

### ISSUE THREAD

**Issue by ruandao** [TencentCloud/tencentcloud-sdk-nodejs#80]
环境:
"tencentcloud-sdk-nodejs": "3.0.266"

报错：

```
error TencentCloudSDKHttpException [Error]: The request is missing a required parameter `SecretId`.
    at SmsClient.parseResponse (/Users/cpu/gitClone/ylz/robot-management/node_modules/tencentcloud-sdk-nodejs/tencentcloud/common/abstract_client.js:138:33)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async SmsClient.doRequest (/Users/cpu/gitClone/ylz/robot-management/node_modules/tencentcloud-sdk-nodejs/tencentcloud/common/abstract_client.js:100:16) {
  requestId: '01d08f06-3ec7-4cbc-878d-ede0cedaf2a3',
  code: 'MissingParameter'
}
```

**Comment by ruandao** [comment]
试了 3.0268 报一样的错误

**Comment by zqfan** [comment]
这种情况说明serverless环境上没能正确获取到密钥信息，如果密钥是从环境变量、配置文件中获取的，请检查下相关的配置
